asciidoctor/asciidoctor-diagram

README.adoc
I got stuck trying to use this extension, as I didn't realise using it was as easy as adding a parameter when executing it.
I got stuck following the examples in this document:
http://asciidoctor.org/news/2014/02/18/plain-text-diagrams-in-asciidoctor/
which was a lot more complicated and failed on asciidoctor 1.5.2
also, it was confusing that this doc referred to asciidoctor-diagrams as an "extension", but in the command line tool's help, the -r parameter added a "library" ... I wasn't sure this was the same thing
Thanks for this really nice tool!
Keep it up!
=> add adciidoc execution instructions

lib/asciidoctor-diagram/extensions.rb
JRuby 9.0.0.0 issues a deprecation warning when loading the asciidoctor-diagram extension:
`warning: Dir.exists? is a deprecated name, use Dir.exist? instead`
And even the http://ruby-doc.org/core-2.2.3/Dir.html#method-c-exist-3F recommends not to use Dir.exists:
>  exists?(file_name) → true or false
> Deprecated method. Don’t use.
This PR simply replaces the call of `Dir.exists?` with the recommended `Dir.exist?`
=> Avoid deprecation warning for Dir.exists with JRuby 9000

lib/asciidoctor-diagram/util/which.rb
The PATH environment variable is not required however this code throws if it is not provided.
=> Allow execution when ENV['PATH'] is not defined

lib/asciidoctor-diagram/extensions.rb, lib/asciidoctor-diagram/mermaid/extension.rb, lib/asciidoctor-diagram/util/which.rb
Store the resolved command in config instead of forcing an assign on an instance variable. The only reason this worked before is because it was exploiting a bug in core. Core was freezing the extension class instead of the extension instance. But we should assume that extension instances are frozen. The config map attached to that class, on the other hand, is owned by that instance and open for modification.
I included the commit from #155 to get the tests to pass.
=> Store resolved command in config

README.adoc, lib/asciidoctor-diagram/syntrax/extension.rb
Hi,
In LaTeX's `syntax` package I'd use something like this `::=` arrow:
But given syntrax doesn't offer support for custom arrows, I do need to set the diagram title to have a visual separation between the element being described and the rule that defines it. This is the `--title` option.
=> Add support for `--title` in syntrax block

README.adoc
From `1.4.0` to `1.5.7`.  
(It took me a while to figure out why I could not use Asciidoctor-diagram with Asciidoctor-revealjs, my problem came from there.)
=> Update the version number for the installation

.travis.yml
* Build using both `Gemfile` and `Gemfile.master` on the latest stable version of Ruby
* Force install bundler < 2 when Ruby version < 2.3 (JRuby)
=> Fix build on master

lib/asciidoctor-diagram/tikz/extension.rb
Without the tikz option, standalone seems to not always properly crop images.  Without the option, my diagram was getting so much extra whitespace on the left that it was at least twice as wide.
This PR should make it so that tikz images don't have extra whitespace around them.
=> Fix tikz crop issues (prevent extraneous whitespace)

.travis.yml, lib/asciidoctor-diagram.rb, lib/asciidoctor-diagram/bpmn.rb, lib/asciidoctor-diagram/bpmn/converter.rb, lib/asciidoctor-diagram/bpmn/extension.rb, spec/bpmn-example.xml, spec/bpmn_spec.rb
This adds support for BPMN-Diagrams through [BPMN-JS](https://bpmn.io/toolkit/bpmn-js/) and a [command line wrapper](https://www.npmjs.com/package/bpmn-js-cmd). It uses puppeteer to do the rendering stuff.
I know XML isn't a format well suited for embedding in documents. But I write a lot of documentation including BPMN-Processes and it would be cool if I could directly reference them in the documentation from the source files instead of having to rerender them to SVG every time somebody makes a change. The macro-form would be perfect here and the preferred way of using this extension. 
BPMN-JS is a battle-tested library and well maintained.
=> Add support for BPMN through bpmn-js

README.adoc
I was going to try and see if I could figure out how to update the version of `bytefield-svg` that you pull in, because I released a bunch of nice new features this weekend, but it looks like you always pull in the most recent one? In any case, my tests of the new features are working in my clone of asciidoctor-diagram.
Here is a tweak to the README that I mentioned in the issue, anyway.
=> Fix link to svg-bytefield in README #276

README.adoc, lib/asciidoctor-diagram/svgbob/converter.rb
issue #270: svgbob is currently not one of the diagram types where options are supported. This pull request adds that in. 
Documentation is from --help text of svgbob.
=> #270 Allow setting options for svgbob

lib/asciidoctor-diagram/tikz/converter.rb
This feature was motived by a need to use TikZ in conjunction with the `tkz-euclide` package. But more broadly, gives you access to the LaTeX preamble section, which therein gives you access to any LaTeX/TikZ package.
```asciidoc
= Hello World
[tikz,"image2",svg, preamble=true]
----
\usepackage{tkz-euclide}
\usepackage{etoolbox}
\usepackage{MnSymbol}
% \usetkzobj{all}
\usetikzlibrary{angles,patterns,calc}
\usepackage[most]{tcolorbox}
\usepackage{pgfplots}
\pgfplotsset{compat=1.7}
~~~~
\begin{tikzpicture}
\tikzset{>=stealth}
% draw axises and labels. We store a single coordinate to have the
% direction of the x axis
\draw[->] (-4,0) -- ++(8,0) coordinate (X) node[below] {$x$};
\draw[->] (0,-4) -- ++(0,8) node[left] {$y$};
\newcommand\CircleRadius{3cm}
\draw (0,0) circle (\CircleRadius);
% …
```
=> Gives access to the preamble section in the generated LaTeX file. 

lib/asciidoctor-diagram/mermaid/converter.rb
Add support for the `mmdc` command line option `--scale`, present since 8.5.2 (mermaid-js/mermaid-cli@6d7cbcb56b501e9c0a84616a33b2ffc21db25361). This allows control over the PNG rendering quality.
=> Add support for mermaid (mmdc) --scale option

.github/workflows/ci-linux.yml
This commit fixes [build failures](https://github.com/asciidoctor/asciidoctor-diagram/actions/runs/389348241) on `master` branch.
=> run apt-get update before attempting to install packages on GitHub Actions

docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/partials/advanced.adoc, docs/modules/ROOT/partials/create_diagram.adoc, docs/modules/ROOT/partials/uris.adoc
This is a proposal to add links to [`jsyntrax`](https://github.com/atp-mipt/jsyntrax) project besides original [`syntrax`](https://github.com/kevinpt/syntrax).
Some reasons:
* `jsyntrax` has the same command line arguments and thus it can be used as a replacement for `syntrax`, particularly in Asciidoctor diagrams.
* Unlike `syntrax` that requires a number of libraries that are tricky to install outside Linux,  `jsyntrax` is a Java program which can run anywhere Java can run.
* `jsyntrax`'s [own documentation](https://atp-mipt.github.io/jsyntrax/) is built with Asciidoctor-diagram.
* [Here](https://courseorchestra.github.io/celesta/en/#CelestaSQL) is another example of documentation built with `jsyntrax`+Asciidoctor-diagram.
=> Add links to jsyntrax project

lib/asciidoctor-diagram/diagram_processor.rb, spec/plantuml_spec.rb, spec/test_helper.rb
This moves wrap_source() inside the begin/rescue block so that exceptions can be shown in the additional source block in the rendered document.
fix #355
=> handle errors in converters when wrapping the source

.github/workflows/ci-linux.yml, .github/workflows/ci-macos.yml
GitHub has recently dropped the support for the `git://` protocol. Running `git clone git://github.com/BurntSushi/erd` yields this:
```sh
Cloning into 'erd'...
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
More background information on this blog: https://github.blog/2021-09-01-improving-git-protocol-security-github/
This PR updates the `git://` protocol to use `HTTPS` instead
=> Update the git:// protocol to use HTTPS instead

deps/plantuml/asciidoctor-diagram-plantuml.gemspec
Just updating PlantUML to 1.2022.12 as it adds some new features I would like to use.
Used the ~~MIT~~ ASL license version from the [download page](https://plantuml.com/download).
=> Update PlantUML to 1.2022.12

lib/asciidoctor-diagram/a2s/converter.rb, lib/asciidoctor-diagram/blockdiag/converter.rb, lib/asciidoctor-diagram/bpmn/converter.rb, lib/asciidoctor-diagram/bytefield/converter.rb, lib/asciidoctor-diagram/dbml/converter.rb, lib/asciidoctor-diagram/diagrams/converter.rb, lib/asciidoctor-diagram/dpic/converter.rb, lib/asciidoctor-diagram/erd/converter.rb, lib/asciidoctor-diagram/gnuplot/converter.rb, lib/asciidoctor-diagram/graphviz/converter.rb, lib/asciidoctor-diagram/graphviz_py/converter.rb, lib/asciidoctor-diagram/http/converter.rb, lib/asciidoctor-diagram/lilypond/converter.rb, lib/asciidoctor-diagram/mermaid/converter.rb, lib/asciidoctor-diagram/msc/converter.rb, lib/asciidoctor-diagram/nomnoml/converter.rb, lib/asciidoctor-diagram/penrose/converter.rb, lib/asciidoctor-diagram/pikchr/converter.rb, lib/asciidoctor-diagram/shaape/converter.rb, lib/asciidoctor-diagram/smcat/converter.rb, lib/asciidoctor-diagram/svgbob/converter.rb, lib/asciidoctor-diagram/symbolator/converter.rb, lib/asciidoctor-diagram/syntrax/converter.rb, lib/asciidoctor-diagram/tikz/converter.rb, lib/asciidoctor-diagram/umlet/converter.rb, lib/asciidoctor-diagram/vega/converter.rb, lib/asciidoctor-diagram/wavedrom/converter.rb
This PR applies the fix for D2 from #410 to all other diagram types.
=> #437 Use diagram source base dir as working directory for all exec'd processes

docs/modules/ROOT/pages/diagram_types/actdiag.adoc
I found this when trying to copy-paste the example
=> Fixing typo in diagram type example

docs/modules/ROOT/partials/uris.adoc
This comment https://github.com/asciidoctor/asciidoctor-maven-examples/pull/244#issue-2116160739 brought attention to how to improve the Java side of things using 'smetana' dot re-implementation.
I don't think we should do more than point to the source docs, and in that sense, I think https://plantuml.com/ is a better starting point for users than the current http://plantuml.sourceforge.net
=> Update PlantUML URL in docs

docs/modules/ROOT/pages/diagram_types/vega.adoc
Currently, https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/vega/ displays like this:
=> vega engine table

lib/asciidoctor-diagram/plantuml/converter.rb
I played around with the native plantuml support some more and would update the error message to mention that a native image is an option. And remove the runtime dependency because now im forced to install them even if i don't use them and as far as i can tell the imports are done in a way where it just fails if you try a diagram without support and telling you to install it.
=> native plantuml support

.github/workflows/ci-linux.yml, .github/workflows/ci-macos.yml
It appears that pikchr.org doesn't want bots fetching the source from their website, as they implemented a javascript bot detection script that makes wget fail.  I had copied this stanza to my own asciidoctor-diagram blog's CI, and started to see failures as of yesterday.  My failing CI run [is here](https://github.com/transactionalblog/blog/actions/runs/17004953108/job/48213190247).
Instead, there's a mirror of the pikchr source at drhsqlite/pikchr, and I don't think github cares if some CI occasionally grabs a source zip. This change works in my blog CI, so you're welcome to the same.
=> Fetch pikchr source from github for CI
